# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_watches_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches_main',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
