# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_watches_main_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches_main',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
