# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_watches_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watches_main',
            name='price',
        ),
    ]
