# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_watches_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_model',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
