SOCIAL_AUTH_VK_OAUTH2_KEY = '5343626'
SOCIAL_AUTH_VK_OAUTH2_SECRET = '9zxBqs4jDjw1C4aAHAl7'

PAYPAL_TEST = True
PAYPAL_WPP_USER = "andreyklimkin-facilitator_api1.yandex.ru"
PAYPAL_WPP_PASSWORD = "2TT699L56V2YTZJ2"
PAYPAL_WPP_SIGNATURE = "AGbfSyexjdjafoy8nmnHvKxfuDlBANMva0A.IT-0dahSPCGdm-IoJI7q"